## Perceptron

#### The Perceptron
###### Its the simplest ANN architecture. it was invented by Frank Rosenbiatt in 1957 and published as Tosenblatt,

In [20]:
import numpy as np 
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use('fivethirtyeight')

In [21]:
class perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f'self.weights: {self.weights}')
        self.eta = eta
        self.epochs = epochs
    
    def activationFunction(self, inputs,weights):
        z = np.dot(inputs,weights)
        return np.where(z>0,1,0)

    def fit(self,x,y):
        self.x = x
        self.y = y

        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]   #conctination
        print(f'x_with_bias :\n{x_with_bias}')
        for epoch in range(self.epochs):
            print(f'for epoch: {self.epochs}')
            y_hat = self.activationFunction(x_with_bias, self.weights)
            print(f'prediction value: \n{y_hat}')
            error = self.y - y_hat
            print(f'error:\n{error}')
            self.weights = self.weights + self.eta*np.dot(x_with_bias.T, error)
            print(f'updated weights: \n {self.weights}')
            print('##############')


    def predict(self,x):
        x_with_bias = np.c_[x, -np.ones((len(self.x),1))] 
        return self.activationFunction(x_with_bias, self.weights)

#### AND Operation:

In [22]:
data = {'x1':[0,0,1,1], 'x2':[0,1,0,1],'y':[0,0,0,1]}
AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [23]:
x = AND.drop('y',axis=1)
x

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [24]:
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [25]:
model = perceptron(eta= 0.5, epochs=10)
model.fit(x,y)

self.weights: [4.39765607e-05 3.86046112e-05 1.87213625e-05]
x_with_bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
 [-0.49995602 -0.4999614   1.00001872]
##############
for epoch: 10
prediction value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
 [4.39765607e-05 3.86046112e-05 5.00018721e-01]
##############
for epoch: 10
prediction value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
 [5.00043977e-01 5.00038605e-01 1.87213625e-05]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
 [4.39765607e-05 3.86046112e-05 1.00001872e+00]
##############
for epoch: 10
prediction value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
 [0.50004398 0.5000386  0.50001872]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
 [4.39765607e-05 3.86046112e-05 1.50001872e+00]
##############
for epoch: 10
prediction value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
 [0.50004398 0.5000386  1.00001872]
##############
for epoch: 10
prediction value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.50004398 0.5000386  1.00001872]
##############
for epoch: 10
prediction value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.50004398 0.5000386  1.00001872]
##############
for epoch: 10
prediction value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.50004398 0.5000386  1.00001872]
##############

In [26]:
model.predict(x)

array([0, 0, 0, 1])

In [27]:
model.weights

array([0.50004398, 0.5000386 , 1.00001872])

### OR Operator

In [29]:
data = {'x1':[0,0,1,1], 'x2':[0,1,0,1],'y':[0,1,1,1]}
OR = pd.DataFrame(data)
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [30]:
x = OR.drop('y',axis=1)
x

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [31]:
y = OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [32]:
model = perceptron(eta= 0.5, epochs=10)
model.fit(x,y)

self.weights: [-6.54032868e-05 -7.45620372e-05 -1.66802919e-05]
x_with_bias :
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 10
prediction value:
[1 0 0 0]
error:
0   -1
1    1
2    1
3    1
Name: y, dtype: int64
updated weights:
 [ 0.9999346   0.99992544 -1.00001668]
##############
for epoch: 10
prediction value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [ 0.9999346   0.99992544 -0.50001668]
##############
for epoch: 10
prediction value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [ 9.99934597e-01  9.99925438e-01 -1.66802919e-05]
##############
for epoch: 10
prediction value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############
for epoch: 10
prediction value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
 [0.9999346  0.99992544 0.49998332]
##############