ITERRATION IN PANDAS

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'a' :[1,2,3],
        'b':[4,5,6],
        'c':['Rose','Lotus','Lily']
}
df = pd.DataFrame(data)
df

   a  b      c
0  1  4   Rose
1  2  5  Lotus
2  3  6   Lily

In [3]:
Change_Indexing = pd.DataFrame(data, index = ['a1','b1','c1'])
Change_Indexing

    a  b      c
a1  1  4   Rose
b1  2  5  Lotus
c1  3  6   Lily

In [4]:
Re_Indexing = Change_Indexing.reindex(['c1','a1','b1'])
Re_Indexing

    a  b      c
c1  3  6   Lily
a1  1  4   Rose
b1  2  5  Lotus

In [5]:
Iter_Data  = df.iterrows()
Iter_Data

In [6]:
for i in Change_Indexing.iterrows():
    print(i)

('a1', a       1
b       4
c    Rose
Name: a1, dtype: object)
('b1', a        2
b        5
c    Lotus
Name: b1, dtype: object)
('c1', a       3
b       6
c    Lily
Name: c1, dtype: object)

In [7]:
for i, j in Change_Indexing.iterrows():
    print(i,j)

print()

a1 a       1
b       4
c    Rose
Name: a1, dtype: object
b1 a        2
b        5
c    Lotus
Name: b1, dtype: object
c1 a       3
b       6
c    Lily
Name: c1, dtype: object

In [8]:
for i in Change_Indexing.itertuples():
    print(i)

print()

Pandas(Index='a1', a=1, b=4, c='Rose')
Pandas(Index='b1', a=2, b=5, c='Lotus')
Pandas(Index='c1', a=3, b=6, c='Lily')

In [9]:
def Sum(x):
    return Change_Indexing.sum()

print(Change_Indexing.apply(Sum))

               a              b              c
a              6              6              6
b             15             15             15
c  RoseLotusLily  RoseLotusLily  RoseLotusLily

In [10]:
df2 =  Change_Indexing[['a','b']]
df2

    a  b
a1  1  4
b1  2  5
c1  3  6

In [ ]:
df2.apply(lambda x : x**2)

    a   b
a1  1  16
b1  4  25
c1  9  36

In [12]:
df3 = Change_Indexing

print(df3.sort_values('c'))

    a  b      c
c1  3  6   Lily
b1  2  5  Lotus
a1  1  4   Rose

In [13]:
print(df3.sort_values('c', ascending=False))

    a  b      c
a1  1  4   Rose
b1  2  5  Lotus
c1  3  6   Lily

In [14]:
print(df3.sort_index())

    a  b      c
a1  1  4   Rose
b1  2  5  Lotus
c1  3  6   Lily

In [15]:
print(df3.sort_index(ascending = False))

    a  b      c
c1  3  6   Lily
b1  2  5  Lotus
a1  1  4   Rose

In [16]:
df4 = pd.DataFrame({'description':[" I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems. I enjoy solving complex problems using efficient algorithms and modern technologies."]})
df4

                                         description
0   I am a dedicated tech enthusiast who loves bu...

In [17]:
pd.set_option ('display.max_colwidth',500)
df4 = pd.DataFrame({'description':[" I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems. I enjoy solving complex problems using efficient algorithms and modern technologies."]})
df4

                                                                                                                                                                                          description
0   I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems. I enjoy solving complex problems using efficient algorithms and modern technologies.

In [18]:
pd.set_option ('display.max_colwidth',500)
df4 = pd.DataFrame({'description':[" I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems.","I'm  learning Python Libraries", "I'm a Data Science Engineer"]})
df4

                                                                                                     description
0   I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems.
1                                                                                 I'm  learning Python Libraries
2                                                                                    I'm a Data Science Engineer

In [19]:

df4['length'] = df4['description'].apply(len)
df4

,description,length
0,I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems.,109
1,I'm learning Python Libraries,30
2,I'm a Data Science Engineer,27

In [20]:
m = "I enjoy solving complex problems using efficient algorithms and modern technologies"
print('total words : ',len(m.split()))

total words :  11

In [21]:
pd.set_option ('display.max_colwidth',500)
df4['Word_Counts'] = df4['description'].apply(lambda x:len(x.split()))
df4

,description,length,Word_Counts
0,I am a dedicated tech enthusiast who loves building scalable applications and exploring intelligent systems.,109,15
1,I'm learning Python Libraries,30,4
2,I'm a Data Science Engineer,27,5