Data Encoding - Label Encoding

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'color':['red','blue','green','green', 'red','blue']})
df

   color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [3]:
from sklearn.preprocessing import LabelEncoder

In [5]:
encoder = LabelEncoder()

In [7]:
encoded =encoder.fit_transform(df['color'])

In [8]:
encoded_df = pd.DataFrame(encoded)

In [9]:
encoded_df

   0
0  2
1  0
2  1
3  1
4  2
5  0

In [11]:
pd.concat([ encoded_df, df], axis=1)

   0  color
0  2    red
1  0   blue
2  1  green
3  1  green
4  2    red
5  0   blue